### ISSUE TITLE
[BUG][MINOR] Crash when scanning folders after deleting an archive

### ISSUE THREAD

**Issue by awused** [seanegoodwin/PandaViewer#31] opened 2015-07-26 10:17 UTC
Traceback (most recent call last):
  File "C:\X\PandaViewer\Program.py", line 358, in image_thread_done
  File "C:\X\PandaViewer\Program.py", line 338, in send_page
  File "C:\X\PandaViewer\Gallery.py", line 117, in get_json
  File "C:\X\PandaViewer\Gallery.py", line 582, in get_file_size
  File "C:\Python27\lib\genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
WindowsError: [Error 2] The system cannot find the file specified: u'Z:\\X\deleted_file.rar'

**Comment by Triskov** [comment] 2015-07-26 21:35
I can confirm this error. I didn't bother to report it though.

**Comment by seanegoodwin** [comment] 2015-07-26 21:54
By deleting an archive, do you mean deleting outside of PandaViewer (using Explorer or whatever)?

**Comment by Triskov** [comment] 2015-07-26 23:10
Yeah, I was deleting some folders so that it wouldn't show multiple times. Some I had where the download I had was like chapter 1, chapter 2, and so on. I deleted them in windows explorer and then when I loaded the page that had those, it would crash because it couldn't find that folder. Simply opening back up lets one continue as normal, so I didn't really see it as an issue.

**Comment by awused** [comment] 2015-07-26 23:50
Yeah it's a minor issue. But I would expect explicitly invoking "scan folders" to look for externally changed files to handle files that went missing.

**Comment by Meowmel** [comment] 2015-07-27 15:17
I think I reported something similar quite some time ago:
A crash happens as well when you deleted a Gallery (from within PV), go to the next site and then back to the site before.

**Comment by seanegoodwin** [comment] 2015-07-27 22:34
> But I would expect explicitly invoking "scan folders" to look for externally changed files to handle files that went missing.

The wording on that option does give that impression. It's not really accurate to what it does anyway - it just triggers a search for new galleries; it doesn't interact with the old ones at all. I'll probably rename it to something.

As for not dealing with filesyetem changes, that's sort of the MO currently. Pandviewer don't expect the files to change while the program is running (unless Pandaviewer does those changes itself of course). I have plans in the work to be able to automatically detect filesystem changes (deleted/renamed files, moving folders, etc). It's relatively low on my non-existent list of things to do however, as it's a relatively large amount of work for a relatively little amount of benefit.

**Comment by awused** [comment] 2015-08-01 09:14
> I think I reported something similar quite some time ago:
> A crash happens as well when you deleted a Gallery (from within PV), go to the next site and then back to the site before.

Confirming this

**Comment by Black-Light** [comment] 2015-08-01 12:05
Also happens when renaming a folder or moving it's location basically anything that affects the path to the gallery (including removing it) causes a crash when you navigate to a page with that gallery on it. This includes searching or changing page.

**Comment by seanegoodwin** [comment] 2015-08-05 07:49
> A crash happens as well when you deleted a Gallery (from within PV), go to the next site and then back to the site before.
Fixed in the latest version.

>Also happens when renaming a folder or moving it's location basically anything that affects the path to the gallery (including removing it) causes a crash when you navigate to a page with that gallery on it. This includes searching or changing page.

Yeah. Any changes to the path will cause problems. 
This is probably the next major feature I'll start working on.

**Comment by seanegoodwin** [comment] 2015-10-10 20:34
PandaViewer should now respond (mostly) correctly to filesystem events. If you see similar/related bugs from now on, please open another issue.

**Closed by seanegoodwin** 2015-10-10 20:34 UTC
