### ISSUE TITLE
[Minor] Duplicate Thumbnails/Info shown

### ISSUE THREAD

**Issue by Triskov** [seanegoodwin/PandaViewer#24] opened 2015-07-18 21:11 UTC
It isn't a problem, but I now have a few where it has two of the same thumbnail and info side by side with each other. No, I don't have actual duplicates, they both open the same folder.
It's a benign mystery.

**Comment by seanegoodwin** [comment] 2015-07-22 00:23
Can you email me a copy of your database? It can be found at C:/Users/<USER>/.lsv/db.sqlite. Email is didyouexpectarealemail@gmail.com

**Comment by Triskov** [comment] 2015-07-22 01:29
Sent

**Comment by seanegoodwin** [comment] 2015-07-24 02:51
The opengl problem you reported is fixed. I'm not entirely sure of the cause of this problem, but it might be fixed in the newest version. Can you give it a try?

**Comment by Triskov** [comment] 2015-07-25 19:08
It wasn't fixed in the newest version, but I deleted the thumbnails and database to start anew and it was no longer present. I'll run to collect the metadata again later today.

**Closed** 2015-09-26 20:33 UTC
