### ISSUE TITLE
Search doesn't like some characters

### ISSUE THREAD

**Issue by Black-Light** [seanegoodwin/PandaViewer#14] opened 2015-06-24 07:06 UTC
When searching for a gallery named **I'm testing** I received 0 results after deleting the first word and searching for **testing** I found the gallery also searching for **Im testing** doesn't work but **m testing** does.

After a bit of testing I found that entering the characters below anywhere in a search will return 0 results.

Commas ( , )
Periods ( . )
Apostrophes ( ' )
Brackets ( [ ] )
Hyphen ( - )

And many others
**Characters that work:**

Letters ( A-Z )
Numbers ( 0-9 )
Underscore ( _ )
Colon ( : ) semicolon does not work
Quotation marks ( " " ) all though they don't seem to do anything

Since these characters are not important in terms of filtering results, you could just write a filter to remove these characters before searching. Brackets and hyphens in particular since tags do not use these characters.

This bug is apparent in the last version as well.

**Update**
Some galleries actually do use hyphens in their tags for instance searching for the artist "Magono Tei" upon typing mago the search will give an auto-complete for "magono-tei" **which returns zero results**

**Comment by seanegoodwin** [comment] 2015-06-25 04:07
![khacdxa](https://cloud.githubusercontent.com/assets/1712653/8346607/41b4ffe0-1acd-11e5-804a-12112e4935e1.png)


Currently working on this. There are a couple of things here. First, the hyphen issue is caused by the regex that looks for filtered tags (e.g. -tag) not working correctly. That should be fixed in the next release. 

As for the characters not working, I'm still doing some investigation. I might just filter them as you suggest.

Oh, and quotes can be used for multi-word tags. E.G. tag_with_spaces or "tag with spaces". This might get deprecated in the future though, underscores is the "official" way of doing this for now.

**Closed** 2015-06-30 19:45 UTC
