### ISSUE TITLE
Crashes Upon Opening.

### ISSUE THREAD

**Issue by Triskov** [seanegoodwin/PandaViewer#35] opened 2015-08-05 03:10 UTC
I downloaded metadata for some new stuff.
Then I sorted by rating, ascending.
Turned a few pages to see how many were without metadata.
Upon turning to the 3rd or 4th page, it crashes.
I start it back up; it crashes immediately.
I'm guessing it's a problem with a gallery.

2015-08-04 21:56:42,760: Database DEBUG Setting up database.
2015-08-04 21:56:42,760: migrate.versioning.util DEBUG Constructing engine
2015-08-04 21:56:42,770: migrate.versioning.repository DEBUG Loading repository Q:\zPrograms\PandaViewer\migrate_repo/...
2015-08-04 21:56:42,770: migrate.versioning.script.base DEBUG Loading script Q:\zPrograms\PandaViewer\migrate_repo/versions\001_migration.py...
2015-08-04 21:56:42,770: migrate.versioning.script.base DEBUG Script Q:\zPrograms\PandaViewer\migrate_repo/versions\001_migration.py loaded successfully
2015-08-04 21:56:42,770: migrate.versioning.script.base DEBUG Loading script Q:\zPrograms\PandaViewer\migrate_repo/versions\002_migration.py...
2015-08-04 21:56:42,770: migrate.versioning.script.base DEBUG Script Q:\zPrograms\PandaViewer\migrate_repo/versions\002_migration.py loaded successfully
2015-08-04 21:56:42,770: migrate.versioning.script.base DEBUG Loading script Q:\zPrograms\PandaViewer\migrate_repo/versions\003_migration.py...
2015-08-04 21:56:42,770: migrate.versioning.script.base DEBUG Script Q:\zPrograms\PandaViewer\migrate_repo/versions\003_migration.py loaded successfully
2015-08-04 21:56:42,770: migrate.versioning.repository DEBUG Repository Q:\zPrograms\PandaViewer\migrate_repo/ loaded successfully
2015-08-04 21:56:42,770: migrate.versioning.repository DEBUG Config: OrderedDict([('db_settings', OrderedDict([('repository_id', 'migrate repository'), ('version_table', 'migrate_version'), ('required_dbs', '[]'), ('use_timestamp_numbering', 'False')]))])
2015-08-04 21:56:42,780: migrate.versioning.util DEBUG Disposing SQLAlchemy engine Engine(sqlite:///C:\Users\BestUser/.lsv\db.sqlite)
2015-08-04 21:56:42,780: migrate.versioning.util DEBUG Constructing engine
2015-08-04 21:56:42,780: migrate.versioning.repository DEBUG Loading repository Q:\zPrograms\PandaViewer\migrate_repo/...
2015-08-04 21:56:42,780: migrate.versioning.script.base DEBUG Loading script Q:\zPrograms\PandaViewer\migrate_repo/versions\001_migration.py...
2015-08-04 21:56:42,780: migrate.versioning.script.base DEBUG Script Q:\zPrograms\PandaViewer\migrate_repo/versions\001_migration.py loaded successfully
2015-08-04 21:56:42,780: migrate.versioning.script.base DEBUG Loading script Q:\zPrograms\PandaViewer\migrate_repo/versions\002_migration.py...
2015-08-04 21:56:42,780: migrate.versioning.script.base DEBUG Script Q:\zPrograms\PandaViewer\migrate_repo/versions\002_migration.py loaded successfully
2015-08-04 21:56:42,780: migrate.versioning.script.base DEBUG Loading script Q:\zPrograms\PandaViewer\migrate_repo/versions\003_migration.py...
2015-08-04 21:56:42,780: migrate.versioning.script.base DEBUG Script Q:\zPrograms\PandaViewer\migrate_repo/versions\003_migration.py loaded successfully
2015-08-04 21:56:42,780: migrate.versioning.repository DEBUG Repository Q:\zPrograms\PandaViewer\migrate_repo/ loaded successfully
2015-08-04 21:56:42,780: migrate.versioning.repository DEBUG Config: OrderedDict([('db_settings', OrderedDict([('repository_id', 'migrate repository'), ('version_table', 'migrate_version'), ('required_dbs', '[]'), ('use_timestamp_numbering', 'False')]))])
2015-08-04 21:56:42,790: migrate.versioning.util DEBUG Disposing SQLAlchemy engine Engine(sqlite:///C:\Users\BestUser/.lsv\db.sqlite)
2015-08-04 21:56:42,790: Program DEBUG Loading config from db.
2015-08-04 21:56:42,790: Database DEBUG New DB session requested from <__main__.Program object at 0x06317530>
2015-08-04 21:56:44,040: Program DEBUG Sending start signal to gallery thread
2015-08-04 21:56:44,040: GalleryThread.GalleryThread INFO Starting to load galleries from database.
2015-08-04 21:56:44,040: Database DEBUG New DB session requested from <GalleryThread(GalleryThread, started daemon 1196)>
2015-08-04 21:56:44,529: GalleryThread.GalleryThread INFO Done loading galleries from database.
2015-08-04 21:56:44,530: GalleryThread.GalleryThread INFO Starting gallery creation from dicts.
2015-08-04 21:56:44,611: GalleryThread.GalleryThread INFO Starting gallery workers
2015-08-04 21:56:44,848: GalleryThread.GalleryThread INFO Gallery workers done.
2015-08-04 21:56:44,849: GalleryThread.GalleryThread DEBUG Done creating galleries from dicts.
2015-08-04 21:56:44,855: Program DEBUG Gallery thread done
2015-08-04 21:56:45,223: Program INFO Search_text: 
2015-08-04 21:56:45,570: Database DEBUG New DB session requested from <ImageThread(ImageThread, started daemon 2176)>
2015-08-04 21:56:45,660: Program DEBUG Image thread done.
2015-08-04 21:56:46,370: Program ERROR Got unhandled exception
Traceback (most recent call last):
  File "Q:\zPrograms\PandaViewer\Program.py", line 404, in image_thread_done
  File "Q:\zPrograms\PandaViewer\Program.py", line 375, in send_page
  File "Q:\zPrograms\PandaViewer\Gallery.py", line 138, in get_json
  File "Q:\zPrograms\PandaViewer\Gallery.py", line 559, in get_file_size
  File "Q:\zPrograms\PandaViewer\Gallery.py", line 494, in files
  File "Q:\zPrograms\PandaViewer\Gallery.py", line 550, in find_files
  File "Q:\zPrograms\PandaViewer\Gallery.py", line 494, in files
  File "Q:\zPrograms\PandaViewer\Gallery.py", line 550, in find_files
  File "Q:\zPrograms\PandaViewer\Gallery.py", line 494, in files
  File "Q:\zPrograms\PandaViewer\Gallery.py", line 550, in find_files
  File "Q:\zPrograms\PandaViewer\Gallery.py", line 494, in files
  File "Q:\zPrograms\PandaViewer\Gallery.py", line 550, in find_files
  File "Q:\zPrograms\PandaViewer\Gallery.py", line 494, in files
  File "Q:\zPrograms\PandaViewer\Gallery.py", line 550, in find_files
.......repeat a few hundred more times
  File "Q:\zPrograms\PandaViewer\Gallery.py", line 494, in files
  File "Q:\zPrograms\PandaViewer\Gallery.py", line 543, in find_files
RuntimeError: maximum recursion depth exceeded while calling a Python object

**Comment by seanegoodwin** [comment] 2015-08-05 03:35
Interesting. Is this reproducible? I don't think it's a probably with your
gallery.

**Comment by Triskov** [comment] 2015-08-05 03:46
I can send you the previous logs of where I was getting metadata if you like.
It certainly crashes every time I open it, so I can't do much with it.
Not sure what else I can do, aside from deleting the db and/or thumbnails.
I don't think downloading a different version would do much of anything.
So, I'm not sure what I can do for it to be reproducible, since I don't know what it is I did to cause it.

**Comment by Triskov** [comment] 2015-08-05 03:52
Here's what the previous log says right before it crashes:
2015-08-04 21:56:29,971: Database DEBUG New DB session requested from <ImageThread(ImageThread, started daemon 800)>
2015-08-04 21:56:30,001: Program DEBUG Image thread done.
2015-08-04 21:56:30,497: Program ERROR Got unhandled exception
Traceback (most recent call last):

**Comment by seanegoodwin** [comment] 2015-08-05 03:57
Don't delete the db (or if you do make a copy first).
I'll see if I can get a build to you to help diagnose this.

**Comment by Triskov** [comment] 2015-08-05 04:34
I renamed the folder and it stopped crashing upon opening, but that may just be a coincidence. 
When I turn the pages with how I have it sorted now, date added descending, it ALWAYS crashes on pages 8 & 9. Pages 1-7 and 10-15 are functional.

**Comment by seanegoodwin** [comment] 2015-08-05 04:36
It's probably something to do with a gallery - doesn't mean the gallery is broken or anything, just something about it is wonky.. I'm adding an extra log statement to figure out which one is causing this. Should have the build in 10 min or so.

**Comment by Triskov** [comment] 2015-08-05 04:38
Yeah, seems so. When I put date added descending, it's only pages 6 & 7 showing the same galleries.

**Comment by seanegoodwin** [comment] 2015-08-05 05:00
Run this and send me the log:
https://github.com/seanegoodwin/PandaViewer/releases/tag/v0.6.2.1

**Comment by Triskov** [comment] 2015-08-05 05:04
Sent

**Comment by seanegoodwin** [comment] 2015-08-05 05:06
Can you look for a gallery called "[Ishikei] TiTiKEi" (probably should've made it print the actual location)? It seems to be causing the problems. I'd like to look at it.

**Comment by Triskov** [comment] 2015-08-05 05:15
The dimensions the cover of that are 5000x2310.
I'm actually probably going to delete this folder because I think I have a superior version, so it may not be an issue after that. I just hadn't gotten around to it yet.

**Comment by seanegoodwin** [comment] 2015-08-05 05:18
Could you zip up the folder and send it to me? I want to see if/why it
crashes at all.

**Comment by Triskov** [comment] 2015-08-05 05:23
I would, but it's far too large with my uploading speed. It's 267MB. Moving to a folder that isn't being monitored or what not, fixed the issue. Going to check the other problem gallery now. I think it might actually be because I had the same folder name inside of a folder. As in, [Ishikei] TiTiKEi/[Ishikei] TiTiKEi.

**Comment by Triskov** [comment] 2015-08-05 05:37
This one other is a mystery. I have a few folders in it and I removed them one by one. Eventually there was nothing in the folder, no hidden or system files even. It still crashed. So I removed folder and then it worked.

**Comment by seanegoodwin** [comment] 2015-08-05 05:54
Does that log for that have anything in it?

**Comment by Triskov** [comment] 2015-08-05 05:55
I don't understand at all. 
So, each of the subfolders work fine by themselves.
By itself, [Shiwasu no Okina] JC Ecchi, with nothing in the folder, crashes PandaViewer.
So I renamed it to [PleaseExplain] JC Ecchi and put find new galleries, and it didn't crashed.
I renamed it back to [Shiwasu no Okina] JC Ecchi....and it crashed.
Maybe something in the database file? I don't know, doesn't show anything different in the log than what I've been pasting.

**Comment by Triskov** [comment] 2015-08-05 05:58
[Shiwasu na Okina] JC Ecchi doesn't crash it either.
Seems to be just that exact spelling.

**Comment by seanegoodwin** [comment] 2015-08-05 05:59
Send me the database if you can. I have no idea what's going on.

**Comment by seanegoodwin** [comment] 2015-08-05 06:01
The only thing I can possible think of is that there is some NTFS mess up going on. I've seen cases where Windows will allow multiple folders with the same name to exist under the same directory when it's not supposed to. This might be something similar. There's nothing in PandaViewer's code that should cause it to crash on a different string name

**Comment by Triskov** [comment] 2015-08-05 06:05
E-mail sent.
I deleted that folder and created one of the same name on a different drive and then pasted it to the same directory and still crashed it. The full path is Q://manga/partial/[Shiwasu no Okina] JC Ecchi

**Comment by seanegoodwin** [comment] 2015-08-05 06:08
Figured it out. I'll have a fix out in the next version.

**Comment by Triskov** [comment] 2015-08-05 06:09
I guess I should have just sent the database from the beginning.

**Comment by seanegoodwin** [comment] 2015-08-05 07:48
Sometime it helps. A lot of the time it's not that helpful.
Fixed in the latest release.

**Closed by seanegoodwin** 2015-08-05 07:48 UTC
